apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reactproject
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: djanicko-test-org/reactrepo
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: group:default/rhdh-team
